# Generated by Django 3.0 on 2020-02-24 22:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('user', 'url_original')},
        ),
    ]
